node {
 try {
 # emailext body: 'test!!', subject: 'Pipeline Job started', to: 'athreya.joshi10@gmail.com'

 
 stage('Git CheckOut') {
    git branch: 'main', url: 'https://github.com/athreya947/Athreya_CaseStudy.git'
 }
 
 def project_path="Jenkins/petclinic-code"
 
 dir(project_path) {
 
 stage('Maven Clean') {
    sh 'mvn clean'
 }
 
  stage('Maven Compile') {
    sh 'mvn compile'
 }
 
 stage('Maven Testing') {
    sh 'mvn test'
 }
 
 stage('Maven Package') {
    sh 'mvn package'
 }
 
 stage('Archive Artifacts') {
    archive 'target/*.war'
 }

 stage('Archive into Artifactory') {
rtUpload (
    serverId: '1',
    spec: '''{
          "files": [
            {
              "pattern": "**/*.war",
			  "target": "generic-snapshot/"
              
            }
         ]
    }''',
 
    // Optional - Associate the uploaded files with the following custom build name and build number,
    // as build artifacts.
    // If not set, the files will be associated with the default build name and build number (i.e the
    // the Jenkins job name and number).
    buildName: 'petclinic',
    buildNumber: '1'
)
}

	  stage('SonarQube Code Check')
    {
        withSonarQubeEnv('SonarQube') {
                sh 'mvn clean package sonar:sonar'
        }
    }
	 

 stage('Getting Ready For Ansible') {
    sh 'cp -rf target/*.war ../../Ansible/Tomcat/files/'
    sh "echo '<h1> Task Build ID: ${env.BUILD_DISPLAY_NAME}</h1>' > ../../Ansible/Tomcat/files/jenkins.html"
 }
  
 }

 def project_ansible="Ansible/Tomcat/"
 dir(project_ansible){
  
 stage('Ansible Deployment') {
    sh 'ansible-playbook webserver.yaml'
 }
 }
 
 } catch (err) {
     emailext body: "${err}", subject: 'Pipeline Job Failed!!', to: 'athreya.joshi10@gmail.com'
	 }
	 
}
